### ISSUE TITLE
Javascript cannot be accessed

### ISSUE THREAD

**Issue by twiesing** [t18d/nG-SetEnvIf#5]
Hello,

thanks for your great work and the NGINX fork!

I have the file `/wp-content/plugins/borlabs-cookie/assets/javascript/borlabs-cookie.min.js`. Unfortunately, this cannot be accessed with the 8G firewall and only returns a 403 error.

If I deactivate the 8G firewall in my NGINX or use the old 7G version, the request works.

Do you need more information?

**Comment by twiesing** [comment]
I think the following is problematic:

```
"~*javascript(?::|%3a).*(?:;|%3b|\)|%29)" 34;
```

(The rule doesn't exist in the original?!)

**Comment by tkb-github** [comment]
> I think the following is problematic:
> 
> ```Nginx
> "~*javascript(?::|%3a).*(?:;|%3b|\)|%29)" 34;
> ```

Nope – if you turn on logging, you’ll see it says

```sh
:bad_request_29:
```

Which means you need to comment out

```Nginx
"~*j\s*a\s*v\s*a" 29;
```


> The rule doesn't exist in the original?!

Both rules are from 8G v1.3. The reason you may not recognise them is because they are greatly simplified in nG-SetEnvIf to mitigate ReDoS problems:

```ApacheConf
RewriteCond %{QUERY_STRING} (j|%6a|%4a)(a|%61|%41)(v|%76|%56)(a|%61|%31)(s|%73|%53)(c|%63|%43)(r|%72|%52)(i|%69|%49)(p|%70|%50)(t|%74|%54)(:|%3a)(.*)(;|%3b|\)|%29) [NC,OR]
```

The bug was actually introduced during the simplification.
